### ISSUE TITLE
Declare docker volumes via config

### ISSUE THREAD

**Issue by cmelion** [cmelion/generator-ng2-webpack#34]
Volumes are currently declared via -v command-line arguments to docker run, making it difficult to add and remove files and directories when changes to the default configs for the image are needed.

```
"docker-start": "docker run --rm --name ${PWD##*/} -i -p 2368:2368 
-v $(pwd)/package.json:/home/yeoman/client/package.json 
-v $(pwd)/src:/home/yeoman/client/src 
-v $(pwd)/api:/home/yeoman/client/api 
cmelion/generator-ng2-webpack:latest"
```
The above would be fine, but the json format does not allow multi-line strings.

Investigate using [docker-run](https://www.npmjs.com/package/docker-run):
```
{
  net: 'bridge',    // network mode (auto | host | bridge). defaults to bridge 
  tty: true,        // be a tty. defaults to false 
  fork: true,       // fork (do not attach stdio). defaults to false 
  remove: true,     // remove the container on stop. defaults to true 
  dns: ['8.8.8.8'], // set custom dns servers 
  ports: {
    8080: 8081      // expose container 8080 to host 8081 
  },
  volumes: {
    '/root': '/tmp', // expose container /root to host /tmp 
    '/root': '/tmp2:ro' // expose container /root to host /tmp2 as read only 
  },
  links: {
    'container-name': 'alias' // link container-name as alias 
  },
  env: {
    FOO: 'bar'      // set env vars 
  },
  entrypoint: '/bin/bash' // override entrypoint on container 
}

```

**Comment by cmelion** [comment]
docker-run is not working as expected.
https://github.com/mafintosh/docker-run/issues/9

**Comment by cmelion** [comment]
switched to using docker-compose.  Configuration is now done via docker-compose.yml:

```
web:
  image: cmelion/generator-ng2-webpack:latest
  volumes:
    - ./package.json:/home/yeoman/client/package.json
    - ./src:/home/yeoman/client/src
    - ./json-server:/home/yeoman/client/json-server
  ports:
    - "2368:2368"
    - "3000:3000"
```
